# Generated by Django 4.1.5 on 2023-06-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=15)),
                ('prouct_line', models.CharField(max_length=20)),
                ('unit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
